#! /usr/bin/env python3
import struct,socket,sys

# defualt HOST e PORT
HOST = "127.0.0.1"  
PORT = 56515  

# **Tipo A**: inviano al server una singola sequenza di byte. Il server deve scrivere tale sequenza nella FIFO `capolet`

import socket

def send_line(sock, line):
    # Calcola la lunghezza della linea come intero a 32 bit e la invia al server
    line_length = len(line)
    sock.sendall(struct.pack("!i",line_length)) 
   
    # Invia la linea al server
    sock.sendall(line.encode())

def main(file_name):
    
    try:
        # Apre il file di testo
        with open(file_name, 'r') as file:
            # Crea il socket TCP

            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
              s.connect((HOST, PORT))

              msg = "a"  
              # converte il messaggio in sequenza di byte
              s.sendall(msg.encode())

              # Invia le linee al server una alla volta
              for line in file:
                  assert(len(line)<2048)
                  send_line(s, line)

              # Chiude il socket
              s.shutdown(socket.SHUT_RDWR)

            # all'uscita dal blocco with viene eseguito s.close()
            # ma per uscire in maniera più pulita dobbiamo
            # usare prima anche shutdown()
            # SHUT_RDWR indica che terminiamo sia lettura che scrittura     
            # s.shutdown(socket.SHUT_RDWR)

        print("Invio completato.")

    except FileNotFoundError:
        print("File non trovato.")


if  len(sys.argv)==2:
  main(sys.argv[1])
else:
  print("Uso:\n\t %s file" % sys.argv[0])
